### ISSUE TITLE
Show also variants which are out of stock

### ISSUE THREAD

**Issue by ChristopherDosin** [Shape-and-Shift/shopware-variant-switch#1]
It would be a nice feature if there would be also a option for show all variants and those ones who are out of stock would be grayed out or disabled.

As seen on the issue tracker: 
https://issues.shopware.com/issues/NEXT-15280

**Comment by vienthuong** [comment]
With the latest PR I also fixed the mentioned issue

![image](https://user-images.githubusercontent.com/22548423/156852611-3f1550f4-415c-471b-9440-2586d6386b93.png)
