### ISSUE TITLE
Hide split variants (Feature Request)

### ISSUE THREAD

**Issue by simgero** [Shape-and-Shift/shopware-variant-switch#2]
Currently, all variants are displayed on the article. However, if the articles are split in the listing, you will see all variants multiple times. Once as a single article and once as a variant selector. 
<img width="1375" alt="grafik" src="https://user-images.githubusercontent.com/13154055/152056421-925bbcd9-6d73-47ec-8f77-7551e6b62fa8.png">

Here an option would be helpful, which shows only the variant attributes on the article for selection, which are not already split.
In this example, in the category the variants are split by color and the sizes are available for selection: 
<img width="1399" alt="grafik" src="https://user-images.githubusercontent.com/13154055/152057795-384d515b-7a83-4053-9a4e-7172125e551a.png">

**Comment by vienthuong** [comment]
Hi @simgero 
Thanks for the great suggestion, I updated it in the latest PR, please have a look :) 

![image](https://user-images.githubusercontent.com/22548423/156852499-75b4fbb0-eed3-417e-be9d-87048a2eaf39.png)

**Comment by simgero** [comment]
Looks perfect. Thanks for this enhancement.
